### ISSUE TITLE
Undo/Redo in constructor for clicking on fill suggestions

### ISSUE THREAD

**Issue by mdirolf** [crosshare-org/crosshare#14]

**Comment by legnes** [comment]
What are your thoughts about a general-purpose undo for the constructor? Or do you think it's more important for things that can change a lot of cells at once (e.g. clicking on suggestions, region cut/paste)?

**Comment by adamthedog** [comment]
I would argue undo/redo should nearly always affect *every* operation. I can't think of any UIs which exclude only certain changes from the history tree (okay, other than maybe one or two spots in git and when you're working with multiple users in office software). That being said, it's worth testing because undo/redo for single cell changes might feel really tedious. If the UI does feel nicer with some exclusions, I'm all for it!

**Comment by legnes** [comment]
Yeah, I think if there's an undo feature people will probably expect it to work all the time! I agree it's really only necessary when you bulk update, but if it's not consistent I bet it will seem confusing or broken...

Partly asking because an "always track everything" undo policy is I think pretty simple to implement if the state is serializable (could be wrong about this!).

That said, I don't think you'd actually want undo to cover everything. Like it should probably ignore changes to the active cell/direction, selection region, and symmetry setting. Not totally sure about clues... 

So yeah do you have thoughts about (in an ideal world) which actions should push to the stack, and which parts of state should be tracked/restored? First guess might be just the grid contents?

**Comment by mdirolf** [comment]
Yeah I think you’re right - probably should cover any changes to grid contents but not other changes like active cell
