### ISSUE TITLE
package.json references prettier but prettier fights with eslint

### ISSUE THREAD

**Issue by glasser** [crosshare-org/crosshare#275]
There's an eslint config file and an eslint script, which suggests running eslint is reasonable. (Though I don't think CI enforces eslint and there are a bunch of errors in `app/pages/error_tests/server/` for me.)

There's also a reference to prettier in package.json which suggests that running prettier might be a good idea.

However if you actually run prettier you'll get into trouble. Notably, the default behavior for prettier is to use double quotes, but the `.eslintrc.json` requires single quotes, so running prettier will break eslint.

**Comment by mdirolf** [comment]
OK I'll be the first to admit that I'm not sure what the state of the art here is and I'd love any nudges in the right direction. My setup currently is that I use vscode and have both the eslint and the "Prettier Eslint" extensions installed. The latter required me to add prettier to package.json IIRC. The eslint extension shows me any eslint errors as I code and the prettier eslint extension formats things nicely on save. I believe that `prettier-eslint` takes care of conflicts like the one you mention by first running prettier and then doing `eslint --fix` on the result to get eslint happy again.

The files in `app/pages/error_tests/` were copied from a nextjs example repo and can probably be dumped at this point - they were just there to make sure that sentry was reporting on different types of errors in prod.

It would be awesome to set this up so that we can enforce conventions and/or fix formatting in CI. If you've got experience with a setup that worked well I would love suggestions or implementation help!

**Comment by mdirolf** [comment]
I think this has all been sorted long ago
