### ISSUE TITLE
hide embed description by default (or change it to say something else)

### ISSUE THREAD

**Issue by RuyiLi** [crosshare-org/crosshare#440]
The current behaviour of embeds spoils some of the clues in the description:

![image](https://github.com/crosshare-org/crosshare/assets/16544254/9eeec303-650d-49b5-9a55-da506e4f7a10)

I think it could be changed to show some basic metadata instead, like the tags/author/difficulty/size

**Comment by mdirolf** [comment]
I think for SEO reasons it's preferable to have some more diverse content there rather than just author/difficulty/size. I guess I don't think of this as really spoiling clues since it's not giving away any of the answers, but I do see your point.

If you include a blog post with your puzzle (can just be a sentence or two if that's all you want) that will get used instead of the clues :).
