### ISSUE TITLE
Filter by crossword difficulty

### ISSUE THREAD

**Issue by hugleo** [crosshare-org/crosshare#441]
Something like that:

https://crosshare.org/rating/easy - Will list all easy crosswords
https://crosshare.org/rating/medium - Will list all medium crosswords
https://crosshare.org/rating/difficult - Will list all difficult crosswords
https://crosshare.org/rating/hard - Will list all very difficult crosswords

**Comment by mdirolf** [comment]
Due to the way difficulty ratings work on Crosshare there is no efficient way to make a list of only puzzles that display as e.g. Medium for you - that's because each difficulty rating is specific to an individual solver. That said, the tag system already automatically groups puzzles into four categories based only on the puzzle's rating, which should be a good approximation of those difficulty ratings but generalized for everybody:

https://crosshare.org/tags/rating-0-1200
https://crosshare.org/tags/rating-1200-1500
https://crosshare.org/tags/rating-1500-1800
https://crosshare.org/tags/rating-1800-up
