### ISSUE TITLE
New Issues With Rebus Entry

### ISSUE THREAD

**Issue by schmidzy** [crosshare-org/crosshare#520]
Hi Mike, noticing some odd rebus behavior today: the "More" button bounces back immediately to the main keyboard unless I long press, and then when I am able to press "Rebus," it also presses "V" on the main keyboard. Video attached. I'm using Chrome on Android 13. Thanks!

https://github.com/crosshare-org/crosshare/assets/165351060/ef8502b4-eab1-476a-a21a-e8d267f31013

**Comment by mdirolf** [comment]
Thanks for the heads up! Are the rest of the keys behaving as expected - the letter keys / backspace I mean?

**Comment by mdirolf** [comment]
It's almost certainly a result of these changes:
https://github.com/crosshare-org/crosshare/commit/3f5eb91a64059548976e2ce113c9085a471af2a7
https://github.com/crosshare-org/crosshare/commit/5adcd1d25a1d0a99f88479ddaec2c639adfb2f1a

My guess is the onClick event isn't getting skipped because those buttons (more / rebus) disappear as soon as the onTouchStart is processed. Not sure why I'm not seeing this on other devices but should be easy enough to use the old logic for more/rebus

**Comment by schmidzy** [comment]
Sure thing! All the other keys are working normally for me; I just poked
around with it some more and it seems the only ones affected are "More,"
"Rebus," and "ABC."

Cheers,
Lydia

**Comment by mdirolf** [comment]
This should be fixed - please give a shout if you have any more issues with it!
